// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomRepo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddCustomRepo'](arg1, arg2, arg3, arg4);
}

export function AddCustomSoftware(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddCustomSoftware'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddFolder(arg1) {
  return window['go']['main']['App']['AddFolder'](arg1);
}

export function ApplyUpdate(arg1) {
  return window['go']['main']['App']['ApplyUpdate'](arg1);
}

export function CheckForUpdate(arg1) {
  return window['go']['main']['App']['CheckForUpdate'](arg1);
}

export function CopyScript(arg1) {
  return window['go']['main']['App']['CopyScript'](arg1);
}

export function CopyToFavorites(arg1, arg2) {
  return window['go']['main']['App']['CopyToFavorites'](arg1, arg2);
}

export function CreateCustomCategory(arg1) {
  return window['go']['main']['App']['CreateCustomCategory'](arg1);
}

export function CreateScriptLib(arg1, arg2) {
  return window['go']['main']['App']['CreateScriptLib'](arg1, arg2);
}

export function DeleteCustomCategory(arg1) {
  return window['go']['main']['App']['DeleteCustomCategory'](arg1);
}

export function DeleteScriptLib(arg1) {
  return window['go']['main']['App']['DeleteScriptLib'](arg1);
}

export function DiscoverRepos(arg1) {
  return window['go']['main']['App']['DiscoverRepos'](arg1);
}

export function DownloadSoftware(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadSoftware'](arg1, arg2, arg3);
}

export function DownloadUpdate(arg1, arg2) {
  return window['go']['main']['App']['DownloadUpdate'](arg1, arg2);
}

export function ExportScripts(arg1, arg2) {
  return window['go']['main']['App']['ExportScripts'](arg1, arg2);
}

export function GetCatalog() {
  return window['go']['main']['App']['GetCatalog']();
}

export function GetCurrentBuild() {
  return window['go']['main']['App']['GetCurrentBuild']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetDefaultInstallDir() {
  return window['go']['main']['App']['GetDefaultInstallDir']();
}

export function GetDefaultScriptsDir() {
  return window['go']['main']['App']['GetDefaultScriptsDir']();
}

export function GetDefaultSoftwareDir() {
  return window['go']['main']['App']['GetDefaultSoftwareDir']();
}

export function GetExeDir() {
  return window['go']['main']['App']['GetExeDir']();
}

export function GetFavoritesSummary() {
  return window['go']['main']['App']['GetFavoritesSummary']();
}

export function GetRecommendedRepos() {
  return window['go']['main']['App']['GetRecommendedRepos']();
}

export function GetRecommendedReposCombined() {
  return window['go']['main']['App']['GetRecommendedReposCombined']();
}

export function GetRepoContents(arg1) {
  return window['go']['main']['App']['GetRepoContents'](arg1);
}

export function GetRepoDetail(arg1) {
  return window['go']['main']['App']['GetRepoDetail'](arg1);
}

export function GetScriptContent(arg1) {
  return window['go']['main']['App']['GetScriptContent'](arg1);
}

export function GetScriptLibContent(arg1) {
  return window['go']['main']['App']['GetScriptLibContent'](arg1);
}

export function GetSoftwareCatalog() {
  return window['go']['main']['App']['GetSoftwareCatalog']();
}

export function GetSoftwareProgress() {
  return window['go']['main']['App']['GetSoftwareProgress']();
}

export function GetSoftwareVersions() {
  return window['go']['main']['App']['GetSoftwareVersions']();
}

export function GetUpdateProgress() {
  return window['go']['main']['App']['GetUpdateProgress']();
}

export function GitAvailable() {
  return window['go']['main']['App']['GitAvailable']();
}

export function HideItem(arg1, arg2) {
  return window['go']['main']['App']['HideItem'](arg1, arg2);
}

export function ImportScriptToLib(arg1, arg2) {
  return window['go']['main']['App']['ImportScriptToLib'](arg1, arg2);
}

export function InstallRepos(arg1, arg2) {
  return window['go']['main']['App']['InstallRepos'](arg1, arg2);
}

export function InvalidateSoftwareVersions() {
  return window['go']['main']['App']['InvalidateSoftwareVersions']();
}

export function IsFavorite(arg1, arg2) {
  return window['go']['main']['App']['IsFavorite'](arg1, arg2);
}

export function IsRepoInstalled(arg1, arg2) {
  return window['go']['main']['App']['IsRepoInstalled'](arg1, arg2);
}

export function IsWebView2Installed() {
  return window['go']['main']['App']['IsWebView2Installed']();
}

export function LibraryCategories() {
  return window['go']['main']['App']['LibraryCategories']();
}

export function ListCustomCategories() {
  return window['go']['main']['App']['ListCustomCategories']();
}

export function ListCustomRepos() {
  return window['go']['main']['App']['ListCustomRepos']();
}

export function ListCustomSoftware() {
  return window['go']['main']['App']['ListCustomSoftware']();
}

export function ListFavorites(arg1) {
  return window['go']['main']['App']['ListFavorites'](arg1);
}

export function ListHidden(arg1) {
  return window['go']['main']['App']['ListHidden'](arg1);
}

export function ListLocalRepos() {
  return window['go']['main']['App']['ListLocalRepos']();
}

export function ListLocalSoftware() {
  return window['go']['main']['App']['ListLocalSoftware']();
}

export function ListScripts(arg1, arg2) {
  return window['go']['main']['App']['ListScripts'](arg1, arg2);
}

export function ListScriptsLib() {
  return window['go']['main']['App']['ListScriptsLib']();
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function PickFile() {
  return window['go']['main']['App']['PickFile']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function RemoveCustomRepo(arg1) {
  return window['go']['main']['App']['RemoveCustomRepo'](arg1);
}

export function RemoveCustomSoftware(arg1) {
  return window['go']['main']['App']['RemoveCustomSoftware'](arg1);
}

export function RemoveFolder(arg1) {
  return window['go']['main']['App']['RemoveFolder'](arg1);
}

export function RemoveRepo(arg1, arg2) {
  return window['go']['main']['App']['RemoveRepo'](arg1, arg2);
}

export function RenameCustomCategory(arg1, arg2) {
  return window['go']['main']['App']['RenameCustomCategory'](arg1, arg2);
}

export function RescanAll() {
  return window['go']['main']['App']['RescanAll']();
}

export function RestoreItem(arg1, arg2) {
  return window['go']['main']['App']['RestoreItem'](arg1, arg2);
}

export function RevealInExplorer(arg1) {
  return window['go']['main']['App']['RevealInExplorer'](arg1);
}

export function RunScript(arg1) {
  return window['go']['main']['App']['RunScript'](arg1);
}

export function SaveScriptLib(arg1, arg2) {
  return window['go']['main']['App']['SaveScriptLib'](arg1, arg2);
}

export function Search(arg1, arg2) {
  return window['go']['main']['App']['Search'](arg1, arg2);
}

export function ToggleFavorite(arg1, arg2) {
  return window['go']['main']['App']['ToggleFavorite'](arg1, arg2);
}
